services:
  backend:
    depends_on:
      - pg
      - cache
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    environment:
      - DATABASE_HOST=db
    networks:
      - app-net
    restart: on-failure
  pg:
    image: postgres:15-alpine
    container_name: pg
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=scram-sha-256
      - POSTGRES_INITDB_ARGS=--auth-host=scram-sha-256
    hostname: db
    networks:
      - app-net
    volumes:
      - panurge:/var/lib/postgresql/data
  cache:
    image: redis:alpine
    container_name: cache
    hostname: redis
    networks:
      - app-net
    command: ['redis-server']

volumes:
  panurge:

networks:
  app-net:
    driver: bridge